--- pycoral_original/libcoral/docker/Dockerfile	2026-02-01 16:58:20.104230000 +0100
+++ pycoral/libcoral/docker/Dockerfile	2026-01-11 11:57:11.671873000 +0100
@@ -15,7 +15,7 @@
     && DEBIAN_FRONTEND=noninteractive apt-get install -y \
       sudo \
       debhelper \
-      python \
+      python3 \
       python3-all \
       python3-numpy \
       python3-setuptools \
@@ -24,6 +24,7 @@
       libpython3-dev \
       libpython3-dev:armhf \
       libpython3-dev:arm64 \
+      python-is-python3 \
       build-essential \
       crossbuild-essential-armhf \
       crossbuild-essential-arm64 \
